services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: main_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser -d main_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:15
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: test_db
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: postgresql+asyncpg://youruser:yourpassword@db:5432/main_db
    command: uvicorn MyService.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  tests:
    build: .
    depends_on:
      - test_db
    environment:
      DB_URL: postgresql+asyncpg://youruser:yourpassword@test_db:5432/test_db
    command: pytest -v -s --disable-warnings

volumes:
  pgdata:
  pgdata_test:
